version: '3'
services:

  go:
    build: 
      context: .
      target: builder
    container_name: '${COMPOSE_PROJECT_NAME}'
    tty: true
    ports:
      - 8080:8080
    volumes:
      - "./:/app"